/// Describes information about the instruction set
pub struct Instruction {
    /// To match each Instruction with a specific opcode
    pub opcode: Opcode,

    /// A string that represents the instruction in a human readable way, eg LD A, (BC)
    pub mnemonic: &'static str,

    /// An optional variable to inform whether the instruction need operand stored in memory
    /// Imm can be either Imm::Eight or Imm::Sixteen depending on whether the instruction needs
    /// respectively an immediate 8-bit operand or an immediate 16-bit operand.
    /// Set to None if the instruction does not require an immediate operand.
    pub operand: Option<Imm>,

    /// An `Operation` enum to describe the type of operation is encoded in the opcode.
    pub operation: Operation,

    /// A list of clock cycles associated to the opcode.
    /// Most opcodes have exactly one opcode, but conditional instructions have two:
    /// clock_cycle[0] stores the clock cycle when the condition is true
    /// and clock_cycle[1] when the condition is false
    /// Unconditional fill the second index with Clock::None
    pub cycles: [Clock; 2],
}

/// Enumerates the instruction speed in clock cycle
pub enum Clock {
    None,
    Four,
    Eight,
    Twelve,
    Sixteen,
    Twenty,
    TwentyFour,
    ThirtyTwo,
}

pub enum Page0 {
    Byte0,
    Byte1,
    Byte2,
    Byte3,
    Byte4,
    Byte5,
    Byte6,
    Byte7,
}

/// Represents the two possible sizes of immediate operands: either 8-bit or 16-bit
pub enum Imm {
    Eight,
    Sixteen,
}

impl Instruction {
    /// Creates an Instruction struct with values given as parameter
    const fn new(
        opcode: Opcode,
        mnemonic: &'static str,
        operand: Option<Imm>,
        operation: Operation,
        cycles: [Clock; 2],
    ) -> Self {
        Self {
            opcode: opcode,
            mnemonic: mnemonic,
            operand: operand,
            operation: operation,
            cycles: cycles,
        }
    }

    /// Returns the instruction with a matching opcode
    pub fn getByOpcode(opcode: Opcode) -> Option<&'static Instruction> {
        for instruction in INSTRUCTIONS {
            if instruction.opcode == opcode {
                return Some(instruction);
            }
        }
        None
    }
}
/// A static array of all the instructions in the instructions set.
static INSTRUCTIONS: &'static [Instruction; 324] = &[
    Instruction::new(
        Opcode::NOP,
        "NOP",
        None,
        Operation::Nop,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_BC_d16,
        "LD BC, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Load16(Target16::BC, Source16::Imm16),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_BC_A,
        "LD (BC), A",
        None,
        Operation::Load8(Target8::Addr(At::BC), Source8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_BC,
        "INC BC",
        None,
        Operation::Inc16(Target16::BC),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_B,
        "INC B",
        None,
        Operation::Inc8(Target8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_B,
        "DEC B",
        None,
        Operation::Dec8(Target8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_B_d8,
        "LD B, {:#04x}",
        Some(Imm::Eight),
        Operation::Load8(Target8::B, Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RLCA,
        "RLCA",
        None,
        Operation::Rlca,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_a16_SP,
        "LD {:#06x}, SP",
        Some(Imm::Sixteen),
        Operation::Load16(Target16::Addr, Source16::SP),
        [Clock::Twenty, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_HL_BC,
        "ADD HL, BC",
        None,
        Operation::Add16(Target16::HL, Source16::BC),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_BC,
        "LD A, (BC)",
        None,
        Operation::Load8(Target8::A, Source8::Addr(At::BC)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_BC,
        "DEC BC",
        None,
        Operation::Dec16(Target16::BC),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_C,
        "INC C",
        None,
        Operation::Inc8(Target8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_C,
        "DEC C",
        None,
        Operation::Dec8(Target8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_C_d8,
        "LD C, {:#04x}",
        Some(Imm::Eight),
        Operation::Load8(Target8::C, Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RRCA,
        "RRCA",
        None,
        Operation::Rrca,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::STOP,
        "STOP",
        None,
        Operation::Stop,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_DE_d16,
        "LD DE, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Load16(Target16::DE, Source16::Imm16),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_DE_A,
        "LD (DE), A",
        None,
        Operation::Load8(Target8::Addr(At::DE), Source8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_DE,
        "INC DE",
        None,
        Operation::Inc16(Target16::DE),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_D,
        "INC D",
        None,
        Operation::Inc8(Target8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_D,
        "DEC D",
        None,
        Operation::Dec8(Target8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_D_d8,
        "LD D, {:#04x}",
        Some(Imm::Eight),
        Operation::Load8(Target8::D, Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RLA,
        "RLA",
        None,
        Operation::Rla,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::JR_r8,
        "JR {:#04x}",
        Some(Imm::Eight),
        Operation::Jr(Condition::Always),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_HL_DE,
        "ADD HL, DE",
        None,
        Operation::Add16(Target16::HL, Source16::DE),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_DE,
        "LD A, (DE)",
        None,
        Operation::Load8(Target8::A, Source8::Addr(At::DE)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_DE,
        "DEC DE",
        None,
        Operation::Dec16(Target16::DE),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_E,
        "INC E",
        None,
        Operation::Inc8(Target8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_E,
        "DEC E",
        None,
        Operation::Dec8(Target8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_E_d8,
        "LD E, {:#04x}",
        Some(Imm::Eight),
        Operation::Load8(Target8::E, Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RRA,
        "RRA",
        None,
        Operation::Rra,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::JR_NZ_r8,
        "JR NZ, {:#04x}",
        Some(Imm::Eight),
        Operation::Jr(Condition::NZ),
        [Clock::Twelve, Clock::Eight],
    ),
    Instruction::new(
        Opcode::LD_HL_d16,
        "LD HL, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Load16(Target16::HL, Source16::Imm16),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::LDI_HL_A,
        "LD (HL+), A",
        None,
        Operation::Load8Inc(Target8::Addr(At::HL), Source8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_HL,
        "INC HL",
        None,
        Operation::Inc16(Target16::HL),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_H,
        "INC H",
        None,
        Operation::Inc8(Target8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_H,
        "DEC H",
        None,
        Operation::Dec8(Target8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_H_d8,
        "LD H, {:#04x}",
        Some(Imm::Eight),
        Operation::Load8(Target8::H, Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::DAA,
        "DAA",
        None,
        Operation::Daa,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::JR_Z_r8,
        "JR Z, {:#04x}",
        Some(Imm::Eight),
        Operation::Jr(Condition::Z),
        [Clock::Twelve, Clock::Eight],
    ),
    Instruction::new(
        Opcode::ADD_HL_HL,
        "ADD HL, HL",
        None,
        Operation::Add16(Target16::HL, Source16::HL),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LDI_A_HL,
        "LD A, (HL+)",
        None,
        Operation::Load8Inc(Target8::A, Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_HL,
        "DEC HL",
        None,
        Operation::Dec16(Target16::HL),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_L,
        "INC L",
        None,
        Operation::Inc8(Target8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_L,
        "DEC L",
        None,
        Operation::Dec8(Target8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_L_d8,
        "LD L, {:#04x}",
        Some(Imm::Eight),
        Operation::Load8(Target8::L, Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::CPL,
        "CPL",
        None,
        Operation::Cpl,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::JR_NC_r8,
        "JR NC, {:#04x}",
        Some(Imm::Eight),
        Operation::Jr(Condition::NC),
        [Clock::Twelve, Clock::Eight],
    ),
    Instruction::new(
        Opcode::LD_SP_d16,
        "LD SP, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Load16(Target16::SP, Source16::Imm16),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::LDD_HL_A,
        "LD (HL-), A",
        None,
        Operation::Load8Dec(Target8::Addr(At::HL), Source8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_SP,
        "INC SP",
        None,
        Operation::Inc16(Target16::SP),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_aHL,
        "INC (HL)",
        None,
        Operation::Inc8(Target8::Addr(At::HL)),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_aHL,
        "DEC (HL)",
        None,
        Operation::Dec8(Target8::Addr(At::HL)),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_aHL_d8,
        "LD (HL), {:#04x}",
        Some(Imm::Eight),
        Operation::Load8(Target8::Addr(At::HL), Source8::Imm8),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::SCF,
        "SCF",
        None,
        Operation::Scf,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::JR_C_r8,
        "JR C, {:#04x}",
        Some(Imm::Eight),
        Operation::Jr(Condition::C),
        [Clock::Twelve, Clock::Eight],
    ),
    Instruction::new(
        Opcode::ADD_HL_SP,
        "ADD HL, SP",
        None,
        Operation::Add16(Target16::HL, Source16::SP),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LDD_A_aHL,
        "LD A, (HL-)",
        None,
        Operation::Load8(Target8::A, Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_SP,
        "DEC SP",
        None,
        Operation::Dec16(Target16::SP),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::INC_A,
        "INC A",
        None,
        Operation::Inc8(Target8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::DEC_A,
        "DEC A",
        None,
        Operation::Dec8(Target8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_d8,
        "LD A, {:#04x}",
        Some(Imm::Eight),
        Operation::Load8(Target8::A, Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::CCF,
        "CCF",
        None,
        Operation::Ccf,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_B_B,
        "LD B, B",
        None,
        Operation::Load8(Target8::B, Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_B_C,
        "LD B, C",
        None,
        Operation::Load8(Target8::B, Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_B_D,
        "LD B, D",
        None,
        Operation::Load8(Target8::B, Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_B_E,
        "LD B, E",
        None,
        Operation::Load8(Target8::B, Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_B_H,
        "LD B, H",
        None,
        Operation::Load8(Target8::B, Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_B_L,
        "LD B, L",
        None,
        Operation::Load8(Target8::B, Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_B_aHL,
        "LD B, (HL)",
        None,
        Operation::Load8(Target8::B, Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_B_A,
        "LD B, A",
        None,
        Operation::Load8(Target8::B, Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_C_B,
        "LD C, B",
        None,
        Operation::Load8(Target8::C, Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_C_C,
        "LD C, C",
        None,
        Operation::Load8(Target8::C, Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_C_D,
        "LD C, D",
        None,
        Operation::Load8(Target8::C, Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_C_E,
        "LD C, E",
        None,
        Operation::Load8(Target8::C, Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_C_H,
        "LD C, H",
        None,
        Operation::Load8(Target8::C, Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_C_L,
        "LD C, L",
        None,
        Operation::Load8(Target8::C, Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_C_aHL,
        "LD C, (HL)",
        None,
        Operation::Load8(Target8::C, Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_C_A,
        "LD C, A",
        None,
        Operation::Load8(Target8::C, Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_D_B,
        "LD D, B",
        None,
        Operation::Load8(Target8::D, Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_D_C,
        "LD D, C",
        None,
        Operation::Load8(Target8::D, Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_D_D,
        "LD D, D",
        None,
        Operation::Load8(Target8::D, Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_D_E,
        "LD D, E",
        None,
        Operation::Load8(Target8::D, Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_D_H,
        "LD D, H",
        None,
        Operation::Load8(Target8::D, Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_D_L,
        "LD D, L",
        None,
        Operation::Load8(Target8::D, Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_D_aHL,
        "LD D, (HL)",
        None,
        Operation::Load8(Target8::D, Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_D_A,
        "LD D, A",
        None,
        Operation::Load8(Target8::D, Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_E_B,
        "LD E, B",
        None,
        Operation::Load8(Target8::E, Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_E_C,
        "LD E, C",
        None,
        Operation::Load8(Target8::E, Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_E_D,
        "LD E, D",
        None,
        Operation::Load8(Target8::E, Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_E_E,
        "LD E, E",
        None,
        Operation::Load8(Target8::E, Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_E_H,
        "LD E, H",
        None,
        Operation::Load8(Target8::E, Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_E_L,
        "LD E, L",
        None,
        Operation::Load8(Target8::E, Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_E_aHL,
        "LD E, (HL)",
        None,
        Operation::Load8(Target8::E, Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_E_A,
        "LD E, A",
        None,
        Operation::Load8(Target8::E, Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_H_B,
        "LD H, B",
        None,
        Operation::Load8(Target8::H, Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_H_C,
        "LD H, C",
        None,
        Operation::Load8(Target8::H, Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_H_D,
        "LD H, D",
        None,
        Operation::Load8(Target8::H, Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_H_E,
        "LD H, E",
        None,
        Operation::Load8(Target8::H, Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_H_H,
        "LD H, H",
        None,
        Operation::Load8(Target8::H, Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_H_L,
        "LD H, L",
        None,
        Operation::Load8(Target8::H, Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_H_aHL,
        "LD H, (HL)",
        None,
        Operation::Load8(Target8::H, Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_H_A,
        "LD H, A",
        None,
        Operation::Load8(Target8::H, Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_L_B,
        "LD L, B",
        None,
        Operation::Load8(Target8::L, Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_L_C,
        "LD L, C",
        None,
        Operation::Load8(Target8::L, Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_L_D,
        "LD L, D",
        None,
        Operation::Load8(Target8::L, Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_L_E,
        "LD L, E",
        None,
        Operation::Load8(Target8::L, Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_L_H,
        "LD L, H",
        None,
        Operation::Load8(Target8::L, Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_L_L,
        "LD L, L",
        None,
        Operation::Load8(Target8::L, Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_L_aHL,
        "LD L, (HL)",
        None,
        Operation::Load8(Target8::L, Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_L_A,
        "LD L, A",
        None,
        Operation::Load8(Target8::L, Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_HL_B,
        "LD (HL), B",
        None,
        Operation::Load8(Target8::Addr(At::HL), Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_HL_C,
        "LD (HL), C",
        None,
        Operation::Load8(Target8::Addr(At::HL), Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_HL_D,
        "LD (HL), D",
        None,
        Operation::Load8(Target8::Addr(At::HL), Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_HL_E,
        "LD (HL), E",
        None,
        Operation::Load8(Target8::Addr(At::HL), Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_HL_H,
        "LD (HL), H",
        None,
        Operation::Load8(Target8::Addr(At::HL), Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_HL_L,
        "LD (HL), L",
        None,
        Operation::Load8(Target8::Addr(At::HL), Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::HALT,
        "HALT",
        None,
        Operation::Halt,
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_HL_A,
        "LD (HL), A",
        None,
        Operation::Load8(Target8::Addr(At::HL), Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_B,
        "LD A, B",
        None,
        Operation::Load8(Target8::A, Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_C,
        "LD A, C",
        None,
        Operation::Load8(Target8::A, Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_D,
        "LD A, D",
        None,
        Operation::Load8(Target8::A, Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_E,
        "LD A, E",
        None,
        Operation::Load8(Target8::A, Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_H,
        "LD A, H",
        None,
        Operation::Load8(Target8::A, Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_L,
        "LD A, L",
        None,
        Operation::Load8(Target8::A, Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_aHL,
        "LD A, (HL)",
        None,
        Operation::Load8(Target8::A, Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_A,
        "LD A, A",
        None,
        Operation::Load8(Target8::A, Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_A_B,
        "ADD A, B",
        None,
        Operation::Add8(Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_A_C,
        "ADD A, C",
        None,
        Operation::Add8(Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_A_D,
        "ADD A, D",
        None,
        Operation::Add8(Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_A_E,
        "ADD A, E",
        None,
        Operation::Add8(Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_A_H,
        "ADD A, H",
        None,
        Operation::Add8(Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_A_L,
        "ADD A, L",
        None,
        Operation::Add8(Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_A_HL,
        "ADD A, (HL)",
        None,
        Operation::Add8(Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_A_A,
        "ADD A, A",
        None,
        Operation::Add8(Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADC_A_B,
        "ADC A, B",
        None,
        Operation::Adc(Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADC_A_C,
        "ADC A, C",
        None,
        Operation::Adc(Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADC_A_D,
        "ADC A, D",
        None,
        Operation::Adc(Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADC_A_E,
        "ADC A, E",
        None,
        Operation::Adc(Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADC_A_H,
        "ADC A, H",
        None,
        Operation::Adc(Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADC_A_L,
        "ADC A, L",
        None,
        Operation::Adc(Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::ADC_A_HL,
        "ADC A, (HL)",
        None,
        Operation::Adc(Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::ADC_A_A,
        "ADC A, A",
        None,
        Operation::Adc(Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SUB_B,
        "SUB B",
        None,
        Operation::Sub(Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SUB_C,
        "SUB C",
        None,
        Operation::Sub(Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SUB_D,
        "SUB D",
        None,
        Operation::Sub(Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SUB_E,
        "SUB E",
        None,
        Operation::Sub(Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SUB_H,
        "SUB H",
        None,
        Operation::Sub(Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SUB_L,
        "SUB L",
        None,
        Operation::Sub(Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SUB_HL,
        "SUB (HL)",
        None,
        Operation::Sub(Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SUB_A,
        "SUB A",
        None,
        Operation::Sub(Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SBC_A_B,
        "SBC A, B",
        None,
        Operation::Sbc(Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SBC_A_C,
        "SBC A, C",
        None,
        Operation::Sbc(Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SBC_A_D,
        "SBC A, D",
        None,
        Operation::Sbc(Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SBC_A_E,
        "SBC A, E",
        None,
        Operation::Sbc(Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SBC_A_H,
        "SBC A, H",
        None,
        Operation::Sbc(Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SBC_A_L,
        "SBC A, L",
        None,
        Operation::Sbc(Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::SBC_A_HL,
        "SBC A, (HL)",
        None,
        Operation::Sbc(Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SBC_A_A,
        "SBC A, A",
        None,
        Operation::Sbc(Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::AND_B,
        "AND B",
        None,
        Operation::And(Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::AND_C,
        "AND C",
        None,
        Operation::And(Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::AND_D,
        "AND D",
        None,
        Operation::And(Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::AND_E,
        "AND E",
        None,
        Operation::And(Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::AND_H,
        "AND H",
        None,
        Operation::And(Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::AND_L,
        "AND L",
        None,
        Operation::And(Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::AND_HL,
        "AND (HL)",
        None,
        Operation::And(Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::AND_A,
        "AND A",
        None,
        Operation::And(Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_B,
        "XOR B",
        None,
        Operation::Xor(Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_C,
        "XOR C",
        None,
        Operation::Xor(Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_D,
        "XOR D",
        None,
        Operation::Xor(Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_E,
        "XOR E",
        None,
        Operation::Xor(Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_H,
        "XOR H",
        None,
        Operation::Xor(Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_L,
        "XOR L",
        None,
        Operation::Xor(Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_HL,
        "XOR (HL)",
        None,
        Operation::Xor(Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_A,
        "XOR A",
        None,
        Operation::Xor(Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::OR_B,
        "OR B",
        None,
        Operation::Or(Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::OR_C,
        "OR C",
        None,
        Operation::Or(Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::OR_D,
        "OR D",
        None,
        Operation::Or(Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::OR_E,
        "OR E",
        None,
        Operation::Or(Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::OR_H,
        "OR H",
        None,
        Operation::Or(Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::OR_L,
        "OR L",
        None,
        Operation::Or(Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::OR_HL,
        "OR (HL)",
        None,
        Operation::Or(Source8::Addr(At::HL)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::OR_A,
        "OR A",
        None,
        Operation::Or(Source8::A),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::CP_B,
        "CP B",
        None,
        Operation::Cp(Source8::B),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::CP_C,
        "CP C",
        None,
        Operation::Cp(Source8::C),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::CP_D,
        "CP D",
        None,
        Operation::Cp(Source8::D),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::CP_E,
        "CP E",
        None,
        Operation::Cp(Source8::E),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::CP_H,
        "CP H",
        None,
        Operation::Cp(Source8::H),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::CP_L,
        "CP L",
        None,
        Operation::Cp(Source8::L),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::CP_HL,
        "CP (HL)",
        None,
        Operation::Cp(Source8::Addr(At::HL)),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::RET_NZ,
        "RET NZ",
        None,
        Operation::Ret(Condition::NZ),
        [Clock::Twenty, Clock::Eight],
    ),
    Instruction::new(
        Opcode::POP_BC,
        "POP BC",
        None,
        Operation::Pop(Source16::BC),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::JP_NZ_a16,
        "JP NZ, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Jp(Condition::NZ, Source16::Imm16),
        [Clock::Sixteen, Clock::Twelve],
    ),
    Instruction::new(
        Opcode::JP_a16,
        "JP {:#06x}",
        Some(Imm::Sixteen),
        Operation::Jp(Condition::Always, Source16::Imm16),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::CALL_NZ_a16,
        "CALL NZ, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Call(Condition::NZ, Source16::Imm16),
        [Clock::TwentyFour, Clock::Twelve],
    ),
    Instruction::new(
        Opcode::PUSH_BC,
        "PUSH BC",
        None,
        Operation::Push(Source16::BC),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::ADD_A_d8,
        "ADD A, {:#04x}",
        Some(Imm::Eight),
        Operation::Add8(Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RST_00H,
        "RST 00H",
        None,
        Operation::Rst(Page0::Byte0),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::RET_Z,
        "RET Z",
        None,
        Operation::Ret(Condition::Z),
        [Clock::Twenty, Clock::Eight],
    ),
    Instruction::new(
        Opcode::RET,
        "RET",
        None,
        Operation::Ret(Condition::Always),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::JP_Z_a16,
        "JP Z, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Jp(Condition::Z, Source16::Imm16),
        [Clock::Sixteen, Clock::Twelve],
    ),
    Instruction::new(
        Opcode::CALL_Z_a16,
        "CALL Z, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Call(Condition::Z, Source16::Imm16),
        [Clock::TwentyFour, Clock::Twelve],
    ),
    Instruction::new(
        Opcode::CALL_a16,
        "CALL {:#06x}",
        Some(Imm::Sixteen),
        Operation::Call(Condition::Always, Source16::Imm16),
        [Clock::TwentyFour, Clock::None],
    ),
    Instruction::new(
        Opcode::ADC_A_d8,
        "ADC A, {:#04x}",
        Some(Imm::Eight),
        Operation::Adc(Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RST_08H,
        "RST 08H",
        None,
        Operation::Rst(Page0::Byte1),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::RET_NC,
        "RET NC",
        None,
        Operation::Ret(Condition::NC),
        [Clock::Twenty, Clock::Eight],
    ),
    Instruction::new(
        Opcode::POP_DE,
        "POP DE",
        None,
        Operation::Pop(Source16::DE),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::JP_NC_a16,
        "JP NC, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Jp(Condition::NC, Source16::Imm16),
        [Clock::Sixteen, Clock::Twelve],
    ),
    Instruction::new(
        Opcode::CALL_NC_a16,
        "CALL NC, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Call(Condition::NC, Source16::Imm16),
        [Clock::TwentyFour, Clock::Twelve],
    ),
    Instruction::new(
        Opcode::PUSH_DE,
        "PUSH DE",
        None,
        Operation::Push(Source16::DE),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::SUB_d8,
        "SUB {:#04x}",
        Some(Imm::Eight),
        Operation::Sub(Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RST_10H,
        "RST 10H",
        None,
        Operation::Rst(Page0::Byte2),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::RET_C,
        "RET C",
        None,
        Operation::Ret(Condition::C),
        [Clock::Twenty, Clock::Eight],
    ),
    Instruction::new(
        Opcode::RETI,
        "RETI",
        None,
        Operation::Reti,
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::JP_C_a16,
        "JP C, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Jp(Condition::C, Source16::Imm16),
        [Clock::Sixteen, Clock::Twelve],
    ),
    Instruction::new(
        Opcode::CALL_C_a16,
        "CALL C, {:#06x}",
        Some(Imm::Sixteen),
        Operation::Call(Condition::C, Source16::Imm16),
        [Clock::TwentyFour, Clock::Twelve],
    ),
    Instruction::new(
        Opcode::SBC_A_d8,
        "SBC A, {:#04x}",
        Some(Imm::Eight),
        Operation::Sbc(Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RST_18H,
        "RST 18H",
        None,
        Operation::Rst(Page0::Byte3),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::LDH_a8_A,
        "LDH {:#04x}, A",
        Some(Imm::Eight),
        Operation::Load8Half(Target8::Addr(At::Imm8), Source8::A),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::POP_HL,
        "POP HL",
        None,
        Operation::Pop(Source16::HL),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_aC_A,
        "LD (C), A",
        None,
        Operation::Load8(Target8::Addr(At::C), Source8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::PUSH_HL,
        "PUSH HL",
        None,
        Operation::Push(Source16::HL),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::AND_d8,
        "AND {:#04x}",
        Some(Imm::Eight),
        Operation::And(Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RST_20H,
        "RST 20H",
        None,
        Operation::Rst(Page0::Byte4),
        [Clock::Sixteen, Clock::None],
    ),
    //TODO: pas certaine de cette instruction
    Instruction::new(
        Opcode::ADD_SP_r8,
        "ADD SP, {:#04x}",
        Some(Imm::Eight),
        Operation::Add16(Target16::SP, Source16::Imm8),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::JP_aHL,
        "JP (HL)",
        None,
        Operation::Jp(Condition::Always, Source16::HL),
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_a16_A,
        "LD {:#06x}",
        Some(Imm::Sixteen),
        Operation::Load8(Target8::Addr(At::Imm16), Source8::A),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_d8,
        "XOR {:#04x}",
        Some(Imm::Eight),
        Operation::Xor(Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RST_28H,
        "RST 20H",
        None,
        Operation::Rst(Page0::Byte5),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::LDH_A_a8,
        "LDH A, {:#04x}",
        Some(Imm::Eight),
        Operation::Load8Half(Target8::A, Source8::Addr(At::Imm8)),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::POP_AF,
        "POP AF",
        None,
        Operation::Pop(Source16::AF),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_aC,
        "LD A, (C)",
        None,
        Operation::Load8(Target8::A, Source8::Addr(At::C)),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::DI,
        "DI",
        None,
        Operation::Di,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::PUSH_AF,
        "PUSH AF",
        None,
        Operation::Push(Source16::AF),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::OR_d8,
        "OR {:#04x}",
        Some(Imm::Eight),
        Operation::Or(Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RST_30H,
        "RST 30H",
        None,
        Operation::Rst(Page0::Byte6),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_HL_SP_r8,
        "LD HL, SP+{:#04x}",
        Some(Imm::Eight),
        Operation::LoadHL(Source16::SP, Source16::Imm8),
        [Clock::Twelve, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_SP_HL,
        "LD SP, HL",
        None,
        Operation::Load16(Target16::SP, Source16::HL),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::LD_A_a16,
        "LD A, {:#08x}",
        Some(Imm::Sixteen),
        Operation::Load8(Target8::A, Source8::Addr(At::Imm16)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::XOR_d8,
        "XOR {:#04x}",
        Some(Imm::Eight),
        Operation::Xor(Source8::Imm8),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::EI,
        "EI",
        None,
        Operation::Ei,
        [Clock::Four, Clock::None],
    ),
    Instruction::new(
        Opcode::CP_d8,
        "CP {:#04x}",
        Some(Imm::Eight),
        Operation::Cp(Source8::Imm8),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RST_38H,
        "RST 38H",
        None,
        Operation::Rst(Page0::Byte7),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::RLC_B,
        "RLC B",
        None,
        Operation::Rlc(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RLC_C,
        "RLC C",
        None,
        Operation::Rlc(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RLC_D,
        "RLC D",
        None,
        Operation::Rlc(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RLC_E,
        "RLC E",
        None,
        Operation::Rlc(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RLC_H,
        "RLC H",
        None,
        Operation::Rlc(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RLC_L,
        "RLC L",
        None,
        Operation::Rlc(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RLC_HL,
        "RLC HL",
        None,
        Operation::Rlc(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::RLC_A,
        "RLC A",
        None,
        Operation::Rlc(Target8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RRC_B,
        "RRC B",
        None,
        Operation::Rrc(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RRC_C,
        "RRC C",
        None,
        Operation::Rrc(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RRC_D,
        "RRC D",
        None,
        Operation::Rrc(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RRC_E,
        "RRC E",
        None,
        Operation::Rrc(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RRC_H,
        "RRC H",
        None,
        Operation::Rrc(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RRC_L,
        "RRC L",
        None,
        Operation::Rrc(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RRC_HL,
        "RRC HL",
        None,
        Operation::Rrc(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::RRC_A,
        "RRC A",
        None,
        Operation::Rrc(Target8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RL_B,
        "RL B",
        None,
        Operation::Rl(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RL_C,
        "RL C",
        None,
        Operation::Rl(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RL_D,
        "RL D",
        None,
        Operation::Rl(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RL_E,
        "RL E",
        None,
        Operation::Rl(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RL_H,
        "RL H",
        None,
        Operation::Rl(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RL_L,
        "RL L",
        None,
        Operation::Rl(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RL_HL,
        "RL HL",
        None,
        Operation::Rl(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::RL_A,
        "RL A",
        None,
        Operation::Rl(Target8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RR_B,
        "RR B",
        None,
        Operation::Rr(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RR_C,
        "RR C",
        None,
        Operation::Rr(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RR_D,
        "RR D",
        None,
        Operation::Rr(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RR_E,
        "RR E",
        None,
        Operation::Rr(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RR_H,
        "RR H",
        None,
        Operation::Rr(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RR_L,
        "RR L",
        None,
        Operation::Rr(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::RR_HL,
        "RR HL",
        None,
        Operation::Rr(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::RR_A,
        "RR A",
        None,
        Operation::Rr(Target8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SLA_B,
        "SLA B",
        None,
        Operation::Sla(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SLA_C,
        "SLA C",
        None,
        Operation::Sla(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SLA_D,
        "SLA D",
        None,
        Operation::Sla(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SLA_E,
        "SLA E",
        None,
        Operation::Sla(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SLA_H,
        "SLA H",
        None,
        Operation::Sla(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SLA_L,
        "SLA L",
        None,
        Operation::Sla(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SLA_HL,
        "SLA HL",
        None,
        Operation::Sla(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::SLA_A,
        "SLA A",
        None,
        Operation::Sla(Target8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRA_B,
        "SRA B",
        None,
        Operation::Sra(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRA_C,
        "SRA C",
        None,
        Operation::Sra(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRA_D,
        "SRA D",
        None,
        Operation::Sra(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRA_E,
        "SRA E",
        None,
        Operation::Sra(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRA_H,
        "SRA H",
        None,
        Operation::Sra(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRA_L,
        "SRA L",
        None,
        Operation::Sra(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRA_HL,
        "SRA HL",
        None,
        Operation::Sra(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::SRA_A,
        "SRA A",
        None,
        Operation::Sra(Target8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SWAP_B,
        "SWAP B",
        None,
        Operation::Swap(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SWAP_C,
        "SWAP C",
        None,
        Operation::Swap(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SWAP_D,
        "SWAP D",
        None,
        Operation::Swap(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SWAP_E,
        "SWAP E",
        None,
        Operation::Swap(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SWAP_H,
        "SWAP H",
        None,
        Operation::Swap(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SWAP_L,
        "SWAP L",
        None,
        Operation::Swap(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SWAP_HL,
        "SWAP HL",
        None,
        Operation::Swap(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::SWAP_A,
        "SWAP A",
        None,
        Operation::Swap(Target8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRL_B,
        "SRL B",
        None,
        Operation::Srl(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRL_C,
        "SRL C",
        None,
        Operation::Srl(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRL_D,
        "SRL D",
        None,
        Operation::Srl(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRL_E,
        "SRL E",
        None,
        Operation::Srl(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRL_H,
        "SRL H",
        None,
        Operation::Srl(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRL_L,
        "SRL L",
        None,
        Operation::Srl(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::SRL_HL,
        "SRL HL",
        None,
        Operation::Srl(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::SRL_A,
        "SRL A",
        None,
        Operation::Srl(Target8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_0_B,
        "BIT 0, B",
        None,
        Operation::Sla(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_0_C,
        "BIT 0, C",
        None,
        Operation::Sla(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_0_D,
        "BIT 0, D",
        None,
        Operation::Sla(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_0_E,
        "BIT 0, E",
        None,
        Operation::Sla(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_0_H,
        "BIT 0, H",
        None,
        Operation::Sla(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_0_L,
        "BIT 0, L",
        None,
        Operation::Sla(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_0_HL,
        "BIT 0, HL",
        None,
        Operation::Sla(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_0_A,
        "BIT 0, A",
        None,
        Operation::Sla(Target8::A),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_1_B,
        "BIT 1,B",
        None,
        Operation::Sra(Target8::B),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_1_C,
        "BIT 1,C",
        None,
        Operation::Sra(Target8::C),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_1_D,
        "BIT 1,D",
        None,
        Operation::Sra(Target8::D),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_1_E,
        "BIT 1,E",
        None,
        Operation::Sra(Target8::E),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_1_H,
        "BIT 1,H",
        None,
        Operation::Sra(Target8::H),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_1_L,
        "BIT 1,L",
        None,
        Operation::Sra(Target8::L),
        [Clock::Eight, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_1_HL,
        "BIT 1,HL",
        None,
        Operation::Sra(Target8::Addr(At::HL)),
        [Clock::Sixteen, Clock::None],
    ),
    Instruction::new(
        Opcode::BIT_1_A,
        "BIT 1,A",
        None,
        Operation::Sra(Target8::A),
        [Clock::Eight, Clock::None],
    ),
];

#[derive(PartialEq)]
pub enum Condition {
    NZ,
    NC,
    C,
    Z,
    Always,
}

#[derive(PartialEq)]
pub enum At {
    HL,
    BC,
    DE,
    Imm16,
    C,
    Imm8,
}

#[derive(PartialEq)]
pub enum Source8 {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    Imm8,
    Addr(At),
}

#[derive(PartialEq)]
pub enum Target8 {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    Addr(At),
}

#[derive(PartialEq)]
pub enum Target16 {
    AF,
    BC,
    DE,
    HL,
    SP,
    Addr,
}

#[derive(PartialEq)]
pub enum Source16 {
    AF,
    BC,
    DE,
    HL,
    SP,
    Imm16,
    Imm8,
}

pub enum Bit {
    ZERO,
    ONE,
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
}

/// Represents all the possible operations from the instruction set
pub enum Operation {
    /// 8-bit load instructions
    Load8(Target8, Source8),

    Load8Half(Target8, Source8),

    Load8Dec(Target8, Source8),

    Load8Inc(Target8, Source8),

    /// 16-bit load instructions
    Load16(Target16, Source16),

    Push(Source16),

    Pop(Source16),

    /// 8-bit arithmetic / logic instructions
    Add8(Source8),

    Adc(Source8),

    Sub(Source8),

    Sbc(Source8),

    And(Source8),

    Xor(Source8),

    Or(Source8),

    Cp(Source8),

    Inc8(Target8),

    Dec8(Target8),

    Daa,

    Cpl,

    /// 16-bit Arithmetic/Logic instructions
    Add16(Target16, Source16),

    Inc16(Target16),

    Dec16(Target16),

    //TODO: RENAME
    LoadHL(Source16, Source16),

    /// Rotate and Shift instructions
    Rlca,

    Rla,

    Rrca,

    Rra,

    Rlc(Target8),

    Rl(Target8),

    Rrc(Target8),

    Rr(Target8),

    Sla(Target8),

    Swap(Target8),

    Sra(Target8),

    Srl(Target8),

    /// Single-bit Operations instructions
    Bit(Bit, Target8),

    Set(Bit, Target8),

    Res(Bit, Target8),

    /// CPU Control instructions
    Ccf,

    Scf,

    Nop,

    Halt,

    Stop,

    Di,

    Ei,

    /// Jump instructions
    Jp(Condition, Source16),

    Jr(Condition),

    Call(Condition, Source16),

    Ret(Condition),

    Reti,

    Rst(Page0),
}

/// Lists all the GameBoy opcode both regular and CB-prefixed
#[allow(non_camel_case_types)]
#[derive(PartialEq)]
pub enum Opcode {
    NOP,
    LD_BC_d16,
    LD_BC_A,
    INC_BC,
    INC_B,
    DEC_B,
    LD_B_d8,
    RLCA,
    LD_a16_SP,
    ADD_HL_BC,
    LD_A_BC,
    DEC_BC,
    INC_C,
    DEC_C,
    LD_C_d8,
    RRCA,
    STOP,
    LD_DE_d16,
    LD_DE_A,
    INC_DE,
    INC_D,
    DEC_D,
    LD_D_d8,
    RLA,
    JR_r8,
    ADD_HL_DE,
    LD_A_DE,
    DEC_DE,
    INC_E,
    DEC_E,
    LD_E_d8,
    RRA,
    JR_NZ_r8,
    LD_HL_d16,
    LDI_HL_A,
    INC_HL,
    INC_H,
    DEC_H,
    LD_H_d8,
    DAA,
    JR_Z_r8,
    ADD_HL_HL,
    LDI_A_HL,
    DEC_HL,
    INC_L,
    DEC_L,
    LD_L_d8,
    CPL,
    JR_NC_r8,
    LD_SP_d16,
    LDD_HL_A,
    INC_SP,
    INC_aHL,
    DEC_aHL,
    LD_aHL_d8,
    SCF,
    JR_C_r8,
    ADD_HL_SP,
    LDD_A_aHL,
    DEC_SP,
    INC_A,
    DEC_A,
    LD_A_d8,
    CCF,
    LD_B_B,
    LD_B_C,
    LD_B_D,
    LD_B_E,
    LD_B_H,
    LD_B_L,
    LD_B_aHL,
    LD_B_A,
    LD_C_B,
    LD_C_C,
    LD_C_D,
    LD_C_E,
    LD_C_H,
    LD_C_L,
    LD_C_aHL,
    LD_C_A,
    LD_D_B,
    LD_D_C,
    LD_D_D,
    LD_D_E,
    LD_D_H,
    LD_D_L,
    LD_D_aHL,
    LD_D_A,
    LD_E_B,
    LD_E_C,
    LD_E_D,
    LD_E_E,
    LD_E_H,
    LD_E_L,
    LD_E_aHL,
    LD_E_A,
    LD_H_B,
    LD_H_C,
    LD_H_D,
    LD_H_E,
    LD_H_H,
    LD_H_L,
    LD_H_aHL,
    LD_H_A,
    LD_L_B,
    LD_L_C,
    LD_L_D,
    LD_L_E,
    LD_L_H,
    LD_L_L,
    LD_L_aHL,
    LD_L_A,
    LD_HL_B,
    LD_HL_C,
    LD_HL_D,
    LD_HL_E,
    LD_HL_H,
    LD_HL_L,
    HALT,
    LD_HL_A,
    LD_A_B,
    LD_A_C,
    LD_A_D,
    LD_A_E,
    LD_A_H,
    LD_A_L,
    LD_A_aHL,
    LD_A_A,
    ADD_A_B,
    ADD_A_C,
    ADD_A_D,
    ADD_A_E,
    ADD_A_H,
    ADD_A_L,
    ADD_A_HL,
    ADD_A_A,
    ADC_A_B,
    ADC_A_C,
    ADC_A_D,
    ADC_A_E,
    ADC_A_H,
    ADC_A_L,
    ADC_A_HL,
    ADC_A_A,
    SUB_B,
    SUB_C,
    SUB_D,
    SUB_E,
    SUB_H,
    SUB_L,
    SUB_HL,
    SUB_A,
    SBC_A_B,
    SBC_A_C,
    SBC_A_D,
    SBC_A_E,
    SBC_A_H,
    SBC_A_L,
    SBC_A_HL,
    SBC_A_A,
    AND_B,
    AND_C,
    AND_D,
    AND_E,
    AND_H,
    AND_L,
    AND_HL,
    AND_A,
    XOR_B,
    XOR_C,
    XOR_D,
    XOR_E,
    XOR_H,
    XOR_L,
    XOR_HL,
    XOR_A,
    OR_B,
    OR_C,
    OR_D,
    OR_E,
    OR_H,
    OR_L,
    OR_HL,
    OR_A,
    CP_B,
    CP_C,
    CP_D,
    CP_E,
    CP_H,
    CP_L,
    CP_HL,
    CP_A,
    RET_NZ,
    POP_BC,
    JP_NZ_a16,
    JP_a16,
    CALL_NZ_a16,
    PUSH_BC,
    ADD_A_d8,
    RST_00H,
    RET_Z,
    RET,
    JP_Z_a16,
    CALL_Z_a16,
    CALL_a16,
    ADC_A_d8,
    RST_08H,
    RET_NC,
    POP_DE,
    JP_NC_a16,
    CALL_NC_a16,
    PUSH_DE,
    SUB_d8,
    RST_10H,
    RET_C,
    RETI,
    JP_C_a16,
    CALL_C_a16,
    SBC_A_d8,
    RST_18H,
    LDH_a8_A,
    POP_HL,
    LD_aC_A,
    PUSH_HL,
    AND_d8,
    RST_20H,
    ADD_SP_r8,
    JP_aHL,
    LD_a16_A,
    XOR_d8,
    RST_28H,
    LDH_A_a8,
    POP_AF,
    LD_A_aC,
    DI,
    PUSH_AF,
    OR_d8,
    RST_30H,
    LD_HL_SP_r8,
    LD_SP_HL,
    LD_A_a16,
    EI,
    CP_d8,
    RST_38H,
    RLC_B,
    RLC_C,
    RLC_D,
    RLC_E,
    RLC_H,
    RLC_L,
    RLC_HL,
    RLC_A,
    RRC_B,
    RRC_C,
    RRC_D,
    RRC_E,
    RRC_H,
    RRC_L,
    RRC_HL,
    RRC_A,
    RL_B,
    RL_C,
    RL_D,
    RL_E,
    RL_H,
    RL_L,
    RL_HL,
    RL_A,
    RR_B,
    RR_C,
    RR_D,
    RR_E,
    RR_H,
    RR_L,
    RR_HL,
    RR_A,
    SLA_B,
    SLA_C,
    SLA_D,
    SLA_E,
    SLA_H,
    SLA_L,
    SLA_HL,
    SLA_A,
    SRA_B,
    SRA_C,
    SRA_D,
    SRA_E,
    SRA_H,
    SRA_L,
    SRA_HL,
    SRA_A,
    SWAP_B,
    SWAP_C,
    SWAP_D,
    SWAP_E,
    SWAP_H,
    SWAP_L,
    SWAP_HL,
    SWAP_A,
    SRL_B,
    SRL_C,
    SRL_D,
    SRL_E,
    SRL_H,
    SRL_L,
    SRL_HL,
    SRL_A,
    BIT_0_B,
    BIT_0_C,
    BIT_0_D,
    BIT_0_E,
    BIT_0_H,
    BIT_0_L,
    BIT_0_HL,
    BIT_0_A,
    BIT_1_B,
    BIT_1_C,
    BIT_1_D,
    BIT_1_E,
    BIT_1_H,
    BIT_1_L,
    BIT_1_HL,
    BIT_1_A,
}
